CONVERSATIONS_DIR = "./conversations"
CONVERSATION_FILE = f"{CONVERSATIONS_DIR}/conversation.json"
DEFAULT_CONFIG_FILE = "./config.yml"
SCREENSHOTS_DIR = "./screenshots"
WEBCAM_MARKER = "__webcam__"
SFX_DIR = "./sfx"
